# Generated by Django 5.2.4 on 2025-08-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
